"use client";

import "../agent-controls.css";
import "../chat-professional.css";
import "../agent-blocked.css";
import "../agent-offer-actions.css";
import { Ban, BarChart3, ClipboardList, Clock3, Eye, EyeOff, Home, Image as ImageIcon, LockKeyhole, MessageSquareText, MoreVertical, Pencil, Plus, Send, ShieldCheck, Trash2, UserRound, XCircle } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { API_URL, api, clearToken, getToken, login, setToken, type Account } from "../api-client";

type AgentOffer={id:string;method:"ATM QR"|"YONO Cash";rate:string;min:string;max:string;available:string;active:boolean};
type TradeOrder={id:string;publicNumber:string;userName:string;userAvatar?:string;paymentMethod:string;amountInr:number;amountUsdt:number;rate:number;status:"active"|"cancelled"|"completed";userBlocked:boolean;unreadCount:number;lastMessage?:string;closedAt?:string|null};
type ChatMessage={id:string;senderId:string;body?:string;imageId?:string;status:"sent"|"delivered"|"seen";createdAt:string};
const money=(value:string|number)=>new Intl.NumberFormat("en-IN").format(Number(value)||0);
const mapOrder=(row:any):TradeOrder=>({id:row.id,publicNumber:String(row.publicNumber||row.public_number||"").padStart(6,"0"),userName:row.userName||"Telegram User",userAvatar:row.userAvatar||"",paymentMethod:row.payment_method||row.paymentMethod,amountInr:Number(row.amount_inr||row.amountInr||0),amountUsdt:Number(row.amount_usdt||row.amountUsdt||0),rate:Number(row.rate||0),status:row.status,userBlocked:Boolean(row.userBlocked),unreadCount:Number(row.unreadCount||0),lastMessage:row.lastMessage||"Order created — waiting for message",closedAt:row.closed_at||row.closedAt||null});

export default function AgentLogin(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(""),[signedIn,setSignedIn]=useState(false),[idBlocked,setIdBlocked]=useState(false);
 const[account,setAccount]=useState<Account|null>(null),[tab,setTab]=useState("Home"),[chatOpen,setChatOpen]=useState(false),[orders,setOrders]=useState<TradeOrder[]>([]),[activeOrder,setActiveOrder]=useState<TradeOrder|null>(null),[messages,setMessages]=useState<ChatMessage[]>([]),[messageText,setMessageText]=useState(""),[orderMenu,setOrderMenu]=useState(false);
 const messagesRef=useRef<HTMLDivElement|null>(null);
 const[showOffer,setShowOffer]=useState(false),[editingOffer,setEditingOffer]=useState<string|null>(null),[method,setMethod]=useState<"ATM QR"|"YONO Cash">("ATM QR"),[rate,setRate]=useState("103.25"),[min,setMin]=useState("5000"),[max,setMax]=useState("200000"),[available,setAvailable]=useState("0"),[offers,setOffers]=useState<AgentOffer[]>([]);
 const[agentName,setAgentName]=useState("Agent"),[completedTrades,setCompletedTrades]=useState("0"),[successRate,setSuccessRate]=useState("0"),[profilePhoto,setProfilePhoto]=useState("");
 const hydrate=(value:Account)=>{setAccount(value);setAgentName(value.displayName||"Agent");setCompletedTrades(String(value.completedTrades||0));setSuccessRate(String(value.successRate||0));setProfilePhoto(value.avatarUrl||"");setIdBlocked(value.blocked)};
 const loadOffers=useCallback(()=>api<any[]>("/agent/offers",{},getToken("agent")).then(rows=>setOffers(rows.map(o=>({id:o.id,method:o.paymentMethod,rate:String(o.rate),min:String(o.minInr),max:String(o.maxInr),available:String(o.availableUsdt),active:o.active})))),[]);
 const loadOrders=useCallback(()=>api<any[]>("/orders",{},getToken("agent")).then(rows=>setOrders(rows.map(mapOrder))),[]);
 const loadMessages=useCallback((orderId:string)=>api<any[]>(`/orders/${orderId}/messages`,{},getToken("agent")).then(rows=>setMessages(rows.map(m=>({id:m.id,senderId:m.senderId,body:m.body||undefined,imageId:m.imageId||undefined,status:m.status,createdAt:m.createdAt})))),[]);
 useEffect(()=>{const token=getToken("agent");if(!token)return;api<Account>("/me",{},token).then(value=>{if(value.role!=="agent")throw new Error("Agent access required");hydrate(value);setSignedIn(true)}).catch(()=>clearToken("agent"))},[]);
 useEffect(()=>{if(!signedIn)return;loadOffers().catch(()=>{});loadOrders().catch(()=>{});const timer=window.setInterval(()=>loadOrders().catch(()=>{}),5000);return()=>window.clearInterval(timer)},[signedIn,loadOffers,loadOrders]);
 useEffect(()=>{if(!signedIn)return;const token=getToken("agent");const socket=new WebSocket(`${API_URL.replace(/^http/,"ws")}/realtime?token=${encodeURIComponent(token)}`);socket.onmessage=()=>{loadOrders().catch(()=>{});if(activeOrder)loadMessages(activeOrder.id).catch(()=>{})};return()=>socket.close()},[signedIn,activeOrder?.id,loadOrders,loadMessages]);
 useEffect(()=>{if(!activeOrder||!chatOpen)return;loadMessages(activeOrder.id).then(()=>api(`/orders/${activeOrder.id}/seen`,{method:"POST"},getToken("agent"))).then(()=>loadOrders()).catch(()=>{});const timer=window.setInterval(()=>loadMessages(activeOrder.id).catch(()=>{}),3000);return()=>window.clearInterval(timer)},[activeOrder?.id,chatOpen,loadMessages,loadOrders]);
 useEffect(()=>{if(messagesRef.current)messagesRef.current.scrollTop=messagesRef.current.scrollHeight},[messages]);
 const openCreate=()=>{setEditingOffer(null);setMethod("ATM QR");setRate("103.25");setMin("5000");setMax("200000");setAvailable("0");setShowOffer(true)};
 const openEdit=(o:AgentOffer)=>{setEditingOffer(o.id);setMethod(o.method);setRate(o.rate);setMin(o.min);setMax(o.max);setAvailable(o.available);setShowOffer(true)};
 const saveOffer=async()=>{try{const body=JSON.stringify({paymentMethod:method,rate:Number(rate),minInr:Number(min),maxInr:Number(max),availableUsdt:Number(available)});await api(editingOffer?`/agent/offers/${editingOffer}`:"/agent/offers",{method:editingOffer?"PATCH":"POST",body},getToken("agent"));await loadOffers();setShowOffer(false)}catch(e){alert(e instanceof Error?e.message:"Could not save order")}};
 const deleteOffer=async(id:string)=>{if(!confirm("Delete this published order from the User Dashboard?"))return;try{await api(`/agent/offers/${id}`,{method:"DELETE"},getToken("agent"));await loadOffers()}catch(e){alert(e instanceof Error?e.message:"Could not delete order")}};
 const openChat=(order:TradeOrder)=>{setActiveOrder(order);setChatOpen(true);setOrderMenu(false)};
 const refreshActive=async()=>{const rows=await api<any[]>("/orders",{},getToken("agent"));const mapped=rows.map(mapOrder);setOrders(mapped);if(activeOrder){const updated=mapped.find(o=>o.id===activeOrder.id);if(updated)setActiveOrder(updated)}};
 const cancelOrRestore=async()=>{if(!activeOrder)return;try{await api(`/orders/${activeOrder.id}/${activeOrder.status==="cancelled"?"restore":"cancel"}`,{method:"POST"},getToken("agent"));setOrderMenu(false);await refreshActive()}catch(e){alert(e instanceof Error?e.message:"Order could not be updated")}};
 const toggleBlock=async()=>{if(!activeOrder)return;try{await api(`/orders/${activeOrder.id}/block-user`,{method:activeOrder.userBlocked?"DELETE":"POST"},getToken("agent"));setActiveOrder({...activeOrder,userBlocked:!activeOrder.userBlocked});setOrderMenu(false);await loadOrders()}catch(e){alert(e instanceof Error?e.message:"User block could not be updated")}};
 const deleteChat=async()=>{if(!activeOrder)return;try{await api(`/orders/${activeOrder.id}`,{method:"DELETE"},getToken("agent"));setChatOpen(false);setActiveOrder(null);await loadOrders()}catch(e){alert(e instanceof Error?e.message:"Chat cannot be deleted yet")}};
 const sendMessage=async()=>{const body=messageText.trim();if(!body||!activeOrder)return;try{await api(`/orders/${activeOrder.id}/messages`,{method:"POST",body:JSON.stringify({body})},getToken("agent"));setMessageText("");await loadMessages(activeOrder.id)}catch(e){alert(e instanceof Error?e.message:"Message not sent")}};
 const sendImage=async(file?:File)=>{if(!file||!activeOrder)return;try{const response=await fetch(`${API_URL}/uploads`,{method:"POST",headers:{Authorization:`Bearer ${getToken("agent")}`,"Content-Type":file.type},body:file});const uploaded=await response.json();if(!response.ok)throw new Error(uploaded.error||"Image upload failed");await api(`/orders/${activeOrder.id}/messages`,{method:"POST",body:JSON.stringify({imageId:uploaded.id})},getToken("agent"));await loadMessages(activeOrder.id)}catch(e){alert(e instanceof Error?e.message:"Image not sent")}};

 if(!signedIn)return <main className="agentLoginPage"><section className="agentLoginCard"><header><img src="/brand.png" alt="India USDT Deal"/><span>INDIA USDT DEAL</span><h1>Agent Portal</h1><p>Secure access for authorized P2P agents only</p></header>{idBlocked&&<div className="agentIdBlocked"><Ban/><b>Agent ID Blocked</b><span>Your access has been disabled by the administrator.</span></div>}<form onSubmit={async e=>{e.preventDefault();setError("");try{const result=await login(email,password);if(result.account.role!=="agent")throw new Error("Agent access required");setToken("agent",result.token);hydrate(result.account);setSignedIn(true)}catch(err){setError(err instanceof Error?err.message:"Login failed")}}}><label><span>Agent email</span><div><UserRound/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your agent email"/></div></label><label><span>Password</span><div><LockKeyhole/><input value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?"text":"password"}/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="agentError">{error}</p>}<button className="agentSubmit">Sign in securely</button></form><footer><ShieldCheck/><p><b>Protected Agent Access</b><span>Never share your login details.</span></p></footer></section></main>;
 if(chatOpen&&activeOrder)return <main className="agentDash"><section className="agentChat"><header><button onClick={()=>setChatOpen(false)}>‹</button><span>{activeOrder.userName.slice(0,2).toUpperCase()}</span><div className="agentChatIdentity"><b>{activeOrder.userName} {activeOrder.userBlocked&&<em>Blocked</em>}</b><small>Order #{activeOrder.publicNumber} · {activeOrder.paymentMethod}</small></div><button className="agentMore" onClick={()=>setOrderMenu(v=>!v)}><MoreVertical/></button>{orderMenu&&<div className="agentActionMenu"><button onClick={cancelOrRestore}><XCircle/>{activeOrder.status==="cancelled"?"Restore order":"Cancel order"}</button><button onClick={toggleBlock}><Ban/>{activeOrder.userBlocked?"Unblock user":"Block user"}</button><button onClick={deleteChat}><Trash2/>Delete chat</button></div>}</header><section className="agentTrade"><div><small>User pays</small><b>₹{money(activeOrder.amountInr)}</b></div><div><small>User receives</small><b>{activeOrder.amountUsdt.toFixed(2)} USDT</b></div></section><aside className="retentionNotice"><Clock3/><span>Chat is kept for 15 days after the order closes. It cannot be deleted earlier.</span></aside><div className="agentMessages" ref={messagesRef}><div className="chatDay">Today</div>{messages.length?messages.map(m=><article key={m.id} className={m.senderId===account?.id?"mine":"theirs"}>{m.imageId&&<img className="chatImage" src={`${API_URL}/uploads/${m.imageId}`} alt="Attachment"/>}{m.body&&<p>{m.body}</p>}<small>{new Date(m.createdAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}{m.senderId===account?.id&&`  ${m.status==="sent"?"✓":m.status==="delivered"?"✓✓":"✓✓ Seen"}`}</small></article>):<div className="agentEmpty">No messages yet. Messages will appear here live.</div>}</div>{activeOrder.status==="active"&&!activeOrder.userBlocked?<form onSubmit={e=>{e.preventDefault();sendMessage()}}><label><ImageIcon/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>sendImage(e.target.files?.[0])}/></label><input value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="Message user…"/><button><Send/></button></form>:<div className="agentStopped">{activeOrder.userBlocked?"Messaging disabled — user blocked":"This order is closed"}</div>}</section></main>;
 return <main className="agentDash"><section className="agentDashboard"><header className="agentDashHead"><div><img src={profilePhoto||"/brand.png"}/><p><b>{agentName}</b><span>Verified agent</span></p></div><button onClick={()=>{clearToken("agent");setSignedIn(false)}}>Sign out</button></header><div className="agentContent">
 {tab==="Home"&&<><section className="agentWelcome"><div><span>VERIFIED AGENT</span><h1>Good day, {agentName}</h1><p>Create and manage your P2P buy orders.</p></div><ShieldCheck/></section><section className="agentStats"><div><b>{orders.length}</b><span>User orders</span></div><div><b>{offers.length}</b><span>Published orders</span></div><div><b>{successRate}%</b><span>Completion</span></div></section><div className="agentSectionTitle"><b>Your P2P Orders</b><button onClick={openCreate}><Plus/> Create order</button></div>{offers.length?offers.map(o=><article className="agentOffer" key={o.id}><span>{o.method}</span><h2>₹{o.rate} <small>/ USDT</small></h2><p>User buy limit ₹{money(o.min)} – ₹{money(o.max)}</p><p>Available {Number(o.available).toFixed(2)} USDT</p><div className="agentOfferFoot"><b>Published on User Dashboard</b><aside><button onClick={()=>openEdit(o)}><Pencil/> Edit</button><button className="delete" onClick={()=>deleteOffer(o.id)}><Trash2/> Delete</button></aside></div></article>):<div className="agentEmpty">Create an ATM QR or YONO Cash order to show it on the User Dashboard.</div>}</>}
 {tab==="Orders"&&<><div className="agentPageTitle"><h1>Orders</h1><p>Active, completed and cancelled trades</p></div><aside className="retentionNotice"><Clock3/><span>Closed orders and chats are retained for 15 days.</span></aside>{orders.length?orders.map(o=><button className="agentOrder" key={o.id} onClick={()=>openChat(o)}><div><span className={o.status}>{o.status}</span><b>{o.userName}{o.userBlocked?" · Blocked":""}</b><small>#{o.publicNumber} · {o.paymentMethod}</small></div><div><b>₹{money(o.amountInr)}</b><small>{o.amountUsdt.toFixed(2)} USDT</small></div></button>):<div className="agentEmpty">No customer orders yet.</div>}</>}
 {tab==="Chats"&&<><div className="agentPageTitle"><h1>Chats</h1><p>Live conversations for real customer orders</p></div>{orders.length?orders.map(o=><button className="agentChatRow" key={o.id} onClick={()=>openChat(o)}><span>{o.userName.slice(0,2).toUpperCase()}<i/></span><div><b>{o.userName}</b><p>{o.lastMessage}</p><small>#{o.publicNumber} · {o.paymentMethod}</small></div>{o.unreadCount>0&&<aside>{o.unreadCount}</aside>}</button>):<div className="agentEmpty">A chat will appear when a user places an order.</div>}</>}
 {tab==="Profile"&&<section className="agentProfilePage"><div className="agentPageTitle"><h1>Agent Profile</h1><p>These details appear on the User Dashboard.</p></div><label className="profilePhotoPicker"><span>{profilePhoto?<img src={profilePhoto}/>:agentName.slice(0,2).toUpperCase()}</span><b>Change profile photo</b><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setProfilePhoto(String(reader.result||""));reader.readAsDataURL(file)}}/></label><label>Agent display name<input value={agentName} onChange={e=>setAgentName(e.target.value)}/></label><div><label>Completed trades<input value={completedTrades} onChange={e=>setCompletedTrades(e.target.value.replace(/[^0-9]/g,""))}/></label><label>Success rate (%)<input value={successRate} onChange={e=>setSuccessRate(e.target.value.replace(/[^0-9.]/g,""))}/></label></div><button onClick={async()=>{try{const value=await api<Account>("/agent/profile",{method:"PATCH",body:JSON.stringify({displayName:agentName,completedTrades:Number(completedTrades),successRate:Number(successRate),avatarUrl:profilePhoto||null})},getToken("agent"));hydrate(value);alert("Profile saved and synced to User Dashboard")}catch(e){alert(e instanceof Error?e.message:"Could not save profile")}}}>Save profile</button></section>}
 </div><nav className="agentNav">{[[Home,"Home"],[ClipboardList,"Orders"],[MessageSquareText,"Chats"],[BarChart3,"Profile"]].map(([Icon,label]:any)=><button key={label} className={tab===label?"active":""} onClick={()=>setTab(label)}><Icon/><span>{label}</span>{label==="Chats"&&orders.reduce((sum,o)=>sum+o.unreadCount,0)>0&&<i>{orders.reduce((sum,o)=>sum+o.unreadCount,0)}</i>}</button>)}</nav>
 {showOffer&&<div className="agentModal"><form onSubmit={e=>{e.preventDefault();saveOffer()}}><button type="button" className="agentClose" onClick={()=>setShowOffer(false)}>×</button><h2>{editingOffer?"Update P2P Order":"Create P2P Order"}</h2><p>Saved changes appear automatically on the User Dashboard.</p><label>Order type<select value={method} onChange={e=>setMethod(e.target.value as any)}><option>ATM QR</option><option>YONO Cash</option></select></label><label>Price per USDT<input value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Available USDT<input value={available} onChange={e=>setAvailable(e.target.value.replace(/[^0-9.]/g,""))}/></label><div><label>Minimum buy limit<input value={min} onChange={e=>setMin(e.target.value)}/></label><label>Maximum buy limit<input value={max} onChange={e=>setMax(e.target.value)}/></label></div><button className="agentPublish">{editingOffer?"Save changes":"Publish order"}</button></form></div>}
 </section></main>;
}
