"use client";
import "../agent-controls.css";
import "../chat-professional.css";
import "../agent-blocked.css";
import "../agent-offer-actions.css";
import { Ban, BarChart3, ClipboardList, Clock3, Eye, EyeOff, Home, Image as ImageIcon, LockKeyhole, MessageSquareText, MoreVertical, Pencil, Plus, Send, ShieldCheck, Trash2, UserRound, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { api, clearToken, getToken, login, setToken, type Account } from "../api-client";

type AgentOrder={id:string;method:"ATM QR"|"YONO Cash";rate:string;min:string;max:string;available:string;active:boolean};
const money=(v:string)=>new Intl.NumberFormat("en-IN").format(Number(v)||0);

export default function AgentLogin(){
 const[id,setId]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[signedIn,setSignedIn]=useState(false),[idBlocked,setIdBlocked]=useState(false);
 const[tab,setTab]=useState("Home"),[showOffer,setShowOffer]=useState(false),[editingOffer,setEditingOffer]=useState<string|null>(null),[method,setMethod]=useState<"ATM QR"|"YONO Cash">("ATM QR"),[rate,setRate]=useState("103.25"),[min,setMin]=useState("80000"),[max,setMax]=useState("200000"),[available,setAvailable]=useState("0"),[offers,setOffers]=useState<AgentOrder[]>([]),[chat,setChat]=useState(false),[text,setText]=useState(""),[messages,setMessages]=useState([{agent:false,text:"Hello, I have placed an order. Please send the QR code."}]);
 const[orderMenu,setOrderMenu]=useState(false),[orderStatus,setOrderStatus]=useState<"Active"|"Cancelled">("Active"),[blocked,setBlocked]=useState(false);
 const[agentName,setAgentName]=useState("Agent"),[completedTrades,setCompletedTrades]=useState("0"),[successRate,setSuccessRate]=useState("0"),[profilePhoto,setProfilePhoto]=useState("");
 const hydrate=(account:Account)=>{setAgentName(account.displayName||"Agent");setCompletedTrades(String(account.completedTrades||0));setSuccessRate(String(account.successRate||0));setProfilePhoto(account.avatarUrl||"");setIdBlocked(account.blocked)};
 useEffect(()=>{const token=getToken("agent");if(!token)return;api<Account>("/me",{},token).then(account=>{if(account.role!=="agent")throw new Error("Agent access required");hydrate(account);setSignedIn(true)}).catch(()=>clearToken("agent"))},[]);
 useEffect(()=>{if(!signedIn)return;api<any[]>("/agent/offers",{},getToken("agent")).then(rows=>setOffers(rows.map(o=>({id:o.id,method:o.paymentMethod,rate:String(o.rate),min:String(o.minInr),max:String(o.maxInr),available:String(o.availableUsdt),active:o.active})))).catch(err=>alert(err instanceof Error?err.message:"Could not load published orders"))},[signedIn]);
 useEffect(()=>{const check=()=>{const value=localStorage.getItem("indiausdt-agent-blocked")==="true";setIdBlocked(value);if(value)setSignedIn(false)};check();const timer=window.setInterval(check,1000);return()=>window.clearInterval(timer)},[]);
 const orders=[{id:"#180000",user:"Rahul K.",method:"ATM QR",amount:"80,000",usdt:"774.82",status:orderStatus},{id:"#179842",user:"Aman S.",method:"YONO Cash",amount:"25,000",usdt:"242.13",status:"Cancelled" as const}];
 const toggleOrder=()=>{const restoring=orderStatus==="Cancelled";setOrderStatus(restoring?"Active":"Cancelled");setOrderMenu(false);setMessages(v=>[...v,{agent:true,text:restoring?"Order restored by agent.":"Order cancelled by agent."}])};
 const toggleBlock=()=>{const unblocking=blocked;setBlocked(!blocked);setOrderMenu(false);setMessages(v=>[...v,{agent:true,text:unblocking?"This user has been unblocked.":"This user has been blocked."}])};
 const openCreate=()=>{setEditingOffer(null);setMethod("ATM QR");setRate("103.25");setMin("5000");setMax("200000");setAvailable("0");setShowOffer(true)};
 const openEdit=(o:AgentOrder)=>{setEditingOffer(o.id);setMethod(o.method);setRate(o.rate);setMin(o.min);setMax(o.max);setAvailable(o.available);setShowOffer(true)};
 const publishOrder=async()=>{try{const body=JSON.stringify({paymentMethod:method,rate:Number(rate),minInr:Number(min),maxInr:Number(max),availableUsdt:Number(available)});const saved=await api<any>(editingOffer?`/agent/offers/${editingOffer}`:"/agent/offers",{method:editingOffer?"PATCH":"POST",body},getToken("agent"));const normalized:AgentOrder={id:saved.id,method:saved.paymentMethod||method,rate:String(saved.rate??rate),min:String(saved.minInr??saved.min_inr??min),max:String(saved.maxInr??saved.max_inr??max),available:String(saved.availableUsdt??saved.available_usdt??available),active:true};setOffers(v=>editingOffer?v.map(o=>o.id===editingOffer?normalized:o):[normalized,...v]);setShowOffer(false);setEditingOffer(null)}catch(err){alert(err instanceof Error?err.message:"Could not save order")}};
 const deleteOffer=async(id:string)=>{if(!window.confirm("Delete this published order? It will also disappear from the User Dashboard."))return;try{await api(`/agent/offers/${id}`,{method:"DELETE"},getToken("agent"));setOffers(v=>v.filter(o=>o.id!==id))}catch(err){alert(err instanceof Error?err.message:"Could not delete order")}};
 if(!signedIn)return <main className="agentLoginPage"><section className="agentLoginCard"><header><img src="/brand.png" alt="India USDT Deal"/><span>INDIA USDT DEAL</span><h1>Agent Portal</h1><p>Secure access for authorized P2P agents only</p></header>{idBlocked&&<div className="agentIdBlocked"><Ban/><b>Agent ID Blocked</b><span>Your access has been disabled by the administrator.</span></div>}<form onSubmit={async e=>{e.preventDefault();setError("");if(!id.trim()||password.length<8){setError("Enter a valid agent email and password.");return}try{const result=await login(id,password);if(result.account.role!=="agent")throw new Error("Agent access required");setToken("agent",result.token);hydrate(result.account);setSignedIn(true)}catch(err){setError(err instanceof Error?err.message:"Login failed")}}}><label><span>Agent email</span><div><UserRound/><input type="email" value={id} onChange={e=>setId(e.target.value)} placeholder="Enter your agent email"/></div></label><label><span>Password</span><div><LockKeyhole/><input value={password} onChange={e=>setPassword(e.target.value)} type={show?"text":"password"} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="agentError">{error}</p>}<button className="agentSubmit" disabled={idBlocked}>Sign in securely</button></form><footer><ShieldCheck/><p><b>Protected Agent Access</b><span>Never share your password, OTP or login details.</span></p></footer></section></main>;
 if(chat)return <main className="agentDash"><section className="agentChat"><header><button onClick={()=>setChat(false)} aria-label="Back">‹</button><span>RK</span><div className="agentChatIdentity"><b>Rahul K. {blocked&&<em>Blocked</em>}</b><small>Order #180000 · ATM QR</small></div><button className="agentMore" onClick={()=>setOrderMenu(v=>!v)} aria-label="Order actions"><MoreVertical/></button>{orderMenu&&<div className="agentActionMenu"><button onClick={toggleOrder}><XCircle/>{orderStatus==="Cancelled"?"Restore order":"Cancel order"}</button><button onClick={toggleBlock}><Ban/>{blocked?"Unblock user":"Block user"}</button></div>}</header><section className="agentTrade"><div><small>User pays</small><b>₹80,000</b></div><div><small>User receives</small><b>774.82 USDT</b></div></section><aside className="retentionNotice"><Clock3/><span>Conversation, order and user data will be automatically deleted 15 days after the order closes.</span></aside><div className="agentMessages"><div className="chatDay">Today</div>{messages.map((m,i)=>m.text.includes(" by agent.")||m.text.includes("been blocked")||m.text.includes("been unblocked")?<div key={i} className="systemEvent"><ShieldCheck/><span>{m.text}</span><small>Just now</small></div>:<article key={i} className={m.agent?"mine":"theirs"}><p>{m.text}</p><small>{m.agent?"3:56 PM  ✓✓":"3:55 PM"}</small></article>)}</div>{orderStatus==="Active"&&!blocked?<form onSubmit={e=>{e.preventDefault();if(!text.trim())return;setMessages(v=>[...v,{agent:true,text}]);setText("")}}><label><ImageIcon/><input type="file" accept="image/*"/></label><input value={text} onChange={e=>setText(e.target.value)} placeholder="Message user…"/><button><Send/></button></form>:<div className="agentStopped">{blocked?"Messaging disabled — user blocked":"This order has been cancelled"}</div>}</section></main>;
 return <main className="agentDash"><section className="agentDashboard"><header className="agentDashHead"><div><img src={profilePhoto||"/brand.png"}/><p><b>{agentName}</b><span>Verified agent</span></p></div><button onClick={()=>{clearToken("agent");setSignedIn(false)}}>Sign out</button></header>
  <div className="agentContent">{tab==="Home"&&<><section className="agentWelcome"><div><span>VERIFIED AGENT</span><h1>Good day, {agentName}</h1><p>Create and manage your P2P buy orders.</p></div><ShieldCheck/></section><section className="agentStats"><div><b>2</b><span>User orders</span></div><div><b>{offers.length}</b><span>Published orders</span></div><div><b>{successRate}%</b><span>Completion</span></div></section><div className="agentSectionTitle"><b>Your P2P Orders</b><button onClick={openCreate}><Plus/> Create order</button></div>{offers.length?offers.map(o=><article className="agentOffer" key={o.id}><span>{o.method}</span><h2>₹{o.rate} <small>/ USDT</small></h2><p>User buy limit ₹{money(o.min)} – ₹{money(o.max)}</p><p>Available {Number(o.available).toFixed(2)} USDT</p><div className="agentOfferFoot"><b>Published on User Dashboard</b><aside><button onClick={()=>openEdit(o)}><Pencil/> Edit</button><button className="delete" onClick={()=>deleteOffer(o.id)}><Trash2/> Delete</button></aside></div></article>):<div className="agentEmpty">Create an ATM QR or YONO Cash order to show it on the User Dashboard.</div>}</>}
  {tab==="Orders"&&<><div className="agentPageTitle"><h1>Orders</h1><p>Active, completed and cancelled trades</p></div><aside className="retentionNotice"><Clock3/><span>Closed orders and related customer data are removed automatically after 15 days.</span></aside>{orders.map(o=><article className="agentOrderWrap" key={o.id}><button className="agentOrder" onClick={()=>o.id==="#180000"&&setChat(true)}><div><span className={o.status.toLowerCase()}>{o.status}</span><b>{o.user}{o.id==="#180000"&&blocked?" · Blocked":""}</b><small>{o.id} · {o.method}</small></div><div><b>₹{o.amount}</b><small>{o.usdt} USDT</small></div></button>{o.id==="#180000"&&<button className="orderMore" onClick={()=>setOrderMenu(v=>!v)} aria-label="Order actions"><MoreVertical/></button>}{o.id==="#180000"&&orderMenu&&<div className="agentActionMenu orderListMenu"><button onClick={toggleOrder}><XCircle/>{orderStatus==="Cancelled"?"Restore order":"Cancel order"}</button><button onClick={toggleBlock}><Ban/>{blocked?"Unblock user":"Block user"}</button></div>}</article>)}</>}
  {tab==="Chats"&&<><div className="agentPageTitle"><h1>Chats</h1><p>Conversations for each customer order</p></div><button className="agentChatRow" onClick={()=>setChat(true)}><span>RK<i/></span><div><b>Rahul K.</b><p>Hello, I have placed an order…</p><small>#180000 · ATM QR</small></div><aside>1</aside></button><button className="agentChatRow"><span>AS</span><div><b>Aman S.</b><p>Order cancelled by user</p><small>#179842 · YONO Cash</small></div></button></>}
  {tab==="Profile"&&<section className="agentProfilePage"><div className="agentPageTitle"><h1>Agent Profile</h1><p>These details will appear on the User Dashboard.</p></div><label className="profilePhotoPicker"><span>{profilePhoto?<img src={profilePhoto}/>:agentName.slice(0,2).toUpperCase()}</span><b>Change profile photo</b><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>setProfilePhoto(String(reader.result||""));reader.readAsDataURL(f)}}/></label><label>Agent display name<input value={agentName} onChange={e=>setAgentName(e.target.value)}/></label><div><label>Completed trades<input value={completedTrades} onChange={e=>setCompletedTrades(e.target.value.replace(/[^0-9]/g,""))} inputMode="numeric"/></label><label>Success rate (%)<input value={successRate} onChange={e=>setSuccessRate(e.target.value.replace(/[^0-9.]/g,""))} inputMode="decimal"/></label></div><section className="profilePreview"><small>User Dashboard preview</small><div><span>{profilePhoto?<img src={profilePhoto}/>:agentName.slice(0,2).toUpperCase()}<i/></span><p><b>{agentName||"Agent name"}</b><em>{completedTrades||0} trades · {successRate||0}% completion</em></p><strong>✓ Verified</strong></div></section><button onClick={async()=>{try{const account=await api<Account>("/agent/profile",{method:"PATCH",body:JSON.stringify({displayName:agentName,completedTrades:Number(completedTrades),successRate:Number(successRate),avatarUrl:profilePhoto||null})},getToken("agent"));hydrate(account);alert("Profile saved and synced to User Dashboard")}catch(err){alert(err instanceof Error?err.message:"Could not save profile")}}}>Save profile</button></section>}</div>
  <nav className="agentNav">{[[Home,"Home"],[ClipboardList,"Orders"],[MessageSquareText,"Chats"],[BarChart3,"Profile"]].map(([Icon,label]:any)=><button key={label} className={tab==label?"active":""} onClick={()=>setTab(label)}><Icon/><span>{label}</span>{label==="Chats"&&<i>1</i>}</button>)}</nav>
  {showOffer&&<div className="agentModal"><form onSubmit={e=>{e.preventDefault();publishOrder()}}><button type="button" className="agentClose" onClick={()=>setShowOffer(false)}>×</button><h2>{editingOffer?"Update P2P Order":"Create P2P Order"}</h2><p>Saved changes appear automatically on the User Dashboard.</p><label>Order type<select value={method} onChange={e=>setMethod(e.target.value as any)}><option>ATM QR</option><option>YONO Cash</option></select></label><label>Price per USDT<input value={rate} onChange={e=>setRate(e.target.value)} inputMode="decimal"/></label><label>Available USDT<input value={available} onChange={e=>setAvailable(e.target.value.replace(/[^0-9.]/g,""))} inputMode="decimal"/></label><div><label>Minimum user buy limit<input value={min} onChange={e=>setMin(e.target.value)} inputMode="numeric"/></label><label>Maximum user buy limit<input value={max} onChange={e=>setMax(e.target.value)} inputMode="numeric"/></label></div><button className="agentPublish">{editingOffer?"Save changes":"Publish order"}</button></form></div>}
 </section></main>;
}
