"use client";
import "./style.css";
import "./sell.css";
import "./agents-manage.css";
import "./links.css";
import { Activity, BadgeIndianRupee, BarChart3, Bot, ChevronRight, ClipboardList, Eye, EyeOff, LayoutDashboard, Link2, LockKeyhole, MessageSquareText, Search, ShieldCheck, Users, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";

const orders=[
 {id:"#180000",user:"Rahul K.",agent:"GlobalTradeBizInc",method:"ATM QR",inr:"₹80,000",usdt:"774.82 USDT",status:"Active"},
 {id:"#179842",user:"Aman S.",agent:"India Cash Desk",method:"YONO Cash",inr:"₹25,000",usdt:"242.13 USDT",status:"Cancelled"},
 {id:"#179801",user:"Sahil M.",agent:"GlobalTradeBizInc",method:"ATM QR",inr:"₹1,20,000",usdt:"1,162.79 USDT",status:"Completed"}
];
export default function AdminControl(){
 const[logged,setLogged]=useState(false),[show,setShow]=useState(false),[tab,setTab]=useState("Dashboard"),[range,setRange]=useState("30 Days"),[query,setQuery]=useState(""),[sellDone,setSellDone]=useState(false),[manageAgent,setManageAgent]=useState(false),[agentBlocked,setAgentBlocked]=useState(false),[supportLink,setSupportLink]=useState("https://t.me/IndiaUSDTDealSupport"),[updatesLink,setUpdatesLink]=useState("https://t.me/IndiaUSDTDeal"),[linksSaved,setLinksSaved]=useState(false);
 const[agentData,setAgentData]=useState({name:"GlobalTradeBizInc",trades:"266",success:"99.72",avatar:"",rate:"103.25"});
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("indiausdt-agent-profile")||"{}");setAgentData(v=>({...v,...p,rate:localStorage.getItem("indiausdt-agent-rate")||v.rate}));setAgentBlocked(localStorage.getItem("indiausdt-agent-blocked")==="true");const links=JSON.parse(localStorage.getItem("indiausdt-public-links")||"{}");if(links.support)setSupportLink(links.support);if(links.updates)setUpdatesLink(links.updates)}catch{}},[tab]);
 if(!logged)return <main className="adminLogin"><section><img src="/brand.png" alt="India USDT Deal"/><span>RESTRICTED ACCESS</span><h1>Admin Control Center</h1><p>Authorized platform administrators only</p><form onSubmit={e=>{e.preventDefault();setLogged(true)}}><label>Admin ID<div><ShieldCheck/><input required placeholder="Enter Admin ID"/></div></label><label>Password<div><LockKeyhole/><input required minLength={6} type={show?"text":"password"} placeholder="Enter secure password"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label><button>Continue securely</button></form><small><LockKeyhole/> This private route is not visible to users or agents.</small></section></main>;
 const nav=[[LayoutDashboard,"Dashboard"],[WalletCards,"Sell USDT"],[Bot,"Agents"],[MessageSquareText,"Chats"],[Link2,"Links"],[Activity,"Activity"]] as const;
 return <main className="adminShell"><aside><header><img src="/brand.png"/><div><b>India USDT Deal</b><span>ADMIN CONTROL</span></div></header><nav>{nav.map(([Icon,name])=><button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}><Icon/><span>{name}</span>{name==="Chats"&&<i>4</i>}</button>)}</nav><footer><span>DK</span><div><b>Super Admin</b><small>Full access</small></div><button onClick={()=>setLogged(false)}>↗</button></footer></aside><section className="adminMain"><header><div><h1>{tab}</h1><p>Platform overview and control</p></div><button className="adminAvatar">DK</button></header><div className="adminBody">
 {tab==="Dashboard"&&<><section className="adminWelcome"><div><small>PLATFORM PERFORMANCE</small><h2>₹13.27 Lakh traded</h2><p>12,845.70 USDT total buy volume</p></div><select value={range} onChange={e=>setRange(e.target.value)}><option>Today</option><option>7 Days</option><option>30 Days</option><option>Custom Date</option></select></section><section className="adminMetrics"><article><span><WalletCards/></span><p>Total Buy</p><b>12,845.70 <small>USDT</small></b><em>+12.4% this month</em></article><article><span><BadgeIndianRupee/></span><p>Total INR</p><b>₹13,26,819</b><em>Across all agents</em></article><article><span><ClipboardList/></span><p>Total Orders</p><b>348</b><em>321 completed</em></article><article><span><Users/></span><p>Active Users</p><b>184</b><em>28 new this month</em></article></section><section className="adminGrid"><article className="volumeCard"><header><div><b>Buy Volume</b><small>Last 7 days · USDT</small></div><BarChart3/></header><div className="bars">{[42,58,46,73,63,88,96].map((h,i)=><span key={i} style={{height:h+"%"}}><i>{[620,842,708,1040,914,1260,1418][i]}</i></span>)}</div><footer>{["Fri","Sat","Sun","Mon","Tue","Wed","Thu"].map(d=><span key={d}>{d}</span>)}</footer></article><article className="statusCard"><b>Order Status</b><div className="donut"><span>348<small>Orders</small></span></div><p><span><i className="green"/>Completed <b>321</b></span><span><i className="orange"/>Active <b>19</b></span><span><i className="red"/>Cancelled <b>8</b></span></p></article></section><section className="adminTable"><header><div><b>Recent Orders</b><small>Latest platform activity</small></div><button onClick={()=>setTab("Orders")}>View all <ChevronRight/></button></header><OrderRows rows={orders}/></section></>}
 {tab==="Orders"&&<><PageTitle title="All Orders" text="Monitor and manage every platform order"/><SearchBox value={query} set={setQuery}/><section className="adminTable"><OrderRows rows={orders.filter(o=>(o.user+o.id+o.agent).toLowerCase().includes(query.toLowerCase()))}/></section></>}
 {tab==="Agents"&&<><PageTitle title="Agents" text="Manage verified P2P agents and performance"/><section className="peopleGrid">{[[agentData.name,"8,920 USDT",`${agentData.trades} trades`,agentData.rate,agentData.avatar],["India Cash Desk","3,412 USDT","94 trades","103.10",""] ,["SecurePay Agent","513 USDT","18 trades","102.95",""]].map((a,i)=><article key={a[0]} className={i===0&&agentBlocked?"blockedAgent":""}><span>{a[4]?<img src={a[4]}/>:a[0].slice(0,2).toUpperCase()}<i/></span><b>{a[0]}</b><small>{i===0&&agentBlocked?"Agent ID Blocked":"Verified agent"}</small><div><p>₹{a[3]}<small>Current rate / USDT</small></p><p>{a[2]}<small>Completed</small></p></div><button onClick={()=>i===0&&setManageAgent(true)}>{i===0?"Manage agent":"View agent"}</button></article>)}</section>{manageAgent&&<div className="manageOverlay"><section><button className="manageClose" onClick={()=>setManageAgent(false)}>×</button><span className="manageAvatar">{agentData.avatar?<img src={agentData.avatar}/>:agentData.name.slice(0,2).toUpperCase()}</span><h2>{agentData.name}</h2><p>Agent ID: AGENT001</p><div><span>Current rate <b>₹{agentData.rate} / USDT</b></span><span>Completed <b>{agentData.trades} trades</b></span></div><button className={agentBlocked?"unblockAgent":"blockAgent"} onClick={()=>{const next=!agentBlocked;localStorage.setItem("indiausdt-agent-blocked",String(next));setAgentBlocked(next);setManageAgent(false)}}>{agentBlocked?"Unblock Agent":"Block Agent"}</button><small>{agentBlocked?"Unblocking restores login access. Orders must be republished by the agent.":"Blocking immediately signs out the agent and removes all their orders from the User Dashboard."}</small></section></div>}</>}
 {tab==="Sell USDT"&&<><PageTitle title="Sell USDT" text="Create and assign a secure USDT sell transaction"/><section className="sellLayout"><form className="sellCard" onSubmit={e=>{e.preventDefault();setSellDone(true)}}><header><span><WalletCards/></span><div><b>New Sell Transaction</b><small>Enter the transaction details below</small></div></header><label>USDT amount<div><input required inputMode="decimal" placeholder="0.00"/><b>USDT</b></div></label><label>Sell rate<div><input required inputMode="decimal" defaultValue="102.80"/><b>INR</b></div></label><div className="sellTwo"><label>Assign agent<select><option>GlobalTradeBizInc</option><option>India Cash Desk</option><option>SecurePay Agent</option></select></label><label>Payout method<select><option>UPI</option><option>Bank Transfer</option></select></label></div><label>Customer reference<input required placeholder="Name or Telegram ID"/></label><aside><span>Estimated payout</span><b>₹1,02,800</b><small>For 1,000 USDT at ₹102.80</small></aside><button>Create sell transaction</button>{sellDone&&<p className="sellSuccess"><ShieldCheck/> Sell transaction created successfully.</p>}</form><aside className="sellInfo"><b>Sell overview</b><div><span>Today sold</span><strong>1,420.50 USDT</strong></div><div><span>Pending payout</span><strong>284.20 USDT</strong></div><div><span>Average rate</span><strong>₹102.74</strong></div><small>Every transaction will appear in the activity log and assigned agent dashboard.</small></aside></section></>}
 {tab==="Users"&&<><PageTitle title="Users" text="Customer accounts, order history and access"/><SearchBox value={query} set={setQuery}/><section className="userList">{[["RK","Rahul K.","12 orders","₹2,84,000"],["AS","Aman S.","5 orders","₹72,500"],["SM","Sahil M.","9 orders","₹1,92,000"]].map(u=><article key={u[1]}><span>{u[0]}</span><p><b>{u[1]}</b><small>{u[2]} · {u[3]}</small></p><em>Active</em><button>•••</button></article>)}</section></>}
 {tab==="Chats"&&<><PageTitle title="Live Conversations" text="Review order conversations across all agents"/><section className="userList">{[["RK","Rahul K. ↔ GlobalTradeBizInc","Please send the QR code.","2"],["AS","Aman S. ↔ India Cash Desk","Order cancelled by user",""],["SM","Sahil M. ↔ GlobalTradeBizInc","Payment completed","1"]].map(c=><article key={c[1]}><span>{c[0]}</span><p><b>{c[1]}</b><small>{c[2]}</small></p>{c[3]&&<i>{c[3]}</i>}<button><ChevronRight/></button></article>)}</section></>}
 {tab==="Links"&&<><PageTitle title="Support Links" text="Manage the links shown on the User Dashboard"/><section className="linksManager"><header><span><Link2/></span><div><b>Public contact links</b><small>Changes will appear in the user Profile and order Help panel.</small></div></header><form onSubmit={e=>{e.preventDefault();localStorage.setItem("indiausdt-public-links",JSON.stringify({support:supportLink,updates:updatesLink}));setLinksSaved(true);window.setTimeout(()=>setLinksSaved(false),2200)}}><label>Help & Support link<div><span>?</span><input required type="url" value={supportLink} onChange={e=>setSupportLink(e.target.value)} placeholder="https://t.me/your_support"/></div><small>Opened when a user taps Help & Support.</small></label><label>Updates Channel link<div><span>↗</span><input required type="url" value={updatesLink} onChange={e=>setUpdatesLink(e.target.value)} placeholder="https://t.me/your_channel"/></div><small>Shown in the User Profile section.</small></label><aside><ShieldCheck/><p><b>Safe link management</b><span>Only use your official Telegram or support URLs.</span></p></aside><button>Save & publish links</button>{linksSaved&&<p className="linksSuccess">✓ Links updated on User Dashboard</p>}</form></section></>}
 {tab==="Activity"&&<><PageTitle title="Activity & Retention" text="Security actions and automatic data cleanup"/><section className="retentionAdmin"><ShieldCheck/><div><b>15-day retention is active</b><p>Closed order conversations and related user transaction data are scheduled for automatic deletion after 15 days.</p></div></section><section className="activityList">{["Admin restored order #180000","Agent blocked user Rahul K.","Order #179842 cancelled","Agent profile updated","Expired conversation data deleted"].map((x,i)=><article key={x}><span>{i+1}</span><p><b>{x}</b><small>{i<2?"Just now":"Today · 2:40 PM"}</small></p></article>)}</section></>}
 </div></section></main>;
}
function PageTitle({title,text}:{title:string,text:string}){return <div className="adminPageTitle"><h2>{title}</h2><p>{text}</p></div>}
function SearchBox({value,set}:{value:string,set:(v:string)=>void}){return <label className="adminSearch"><Search/><input value={value} onChange={e=>set(e.target.value)} placeholder="Search by name, agent or order ID"/></label>}
function OrderRows({rows}:{rows:typeof orders}){return <div className="orderRows">{rows.map(o=><article key={o.id}><span className={o.status.toLowerCase()}>{o.status}</span><p><b>{o.user}</b><small>{o.id} · {o.method}</small></p><p><b>{o.inr}</b><small>{o.usdt}</small></p><p><b>{o.agent}</b><small>Agent</small></p><button>•••</button></article>)}</div>}
